protocols:
  - id: csp
    name: Chat Server Protocol
    sections:
      - csp.yml
      - csp-e2e.proto
      - csp-e2e-fs.proto

  - id: md
    name: Multi-Device Protocol
    sections:
      - md.md
      - md-d2m.yml
      - md-d2m.proto
      - md-d2d.proto
      - md-d2d-sync.proto
      - md-d2d-rendezvous.yml
      - md-d2d-rendezvous.proto
      - md-d2d-join.proto
      - md-d2d-history.proto

  - id: o2o-call
    name: 1:1 Call Protocol
    sections:
      - o2o-call.proto

  - id: group-call
    name: Group Call Protocol
    sections:
      - group-call.proto
      - group-call.yml

  - id: url-payloads
    name: URL Payloads
    sections:
      - url-payloads.proto

  - id: common
    name: Common Structures and Messages
    sections:
      - common.proto
      - extra.yml

  - id: guidelines-issues
    name: Guidelines and Issues
    sections:
      - crypto.md
      - issues.md
